name: Test

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run-go-tests:
    # Name the Job
    name: Go Tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run Tests (with coverage report)
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
